module PetsHelper
  def breed_option
    [
      ['Affenpinscher', 'Affenpinscher'],
      ['Afghan Hound', 'Afghan Hound'],
      ['Airedale Terrier', 'Airedale Terrier'],
      ['Akita', 'Akita'],
      ['Alaskan Malamute', 'Alaskan Malamute'],
      ['American Cocker Spaniel', 'American Cocker Spaniel'],
      ['American English Coonhound', 'American English Coonhound'],
      ['American Eskimo Dog-Miniature', 'American Eskimo Dog-Miniature'],
      ['American Eskimo Dog-Standard', 'American Eskimo Dog-Standard'],
      ['American Eskimo Dog-Toy', 'American Eskimo Dog-Toy'],
      ['American Foxhound', 'American Foxhound'],
      ['American Staffordshire Terrier', 'American Staffordshire Terrier'],
      ['American Water Spaniel', 'American Water Spaniel'],
      ['Anatolian Shepherd', 'Anatolian Shepherd'],
      ['Appenzeller Sennenhunde', 'Appenzeller Sennenhunde'],
      ['Australian Cattle Dog', 'Australian Cattle Dog'],
      ['Australian Shepherd', 'Australian Shepherd'],
      ['Australian Terrier', 'Australian Terrier'],
      ['Barbet', 'Barbet'],
      ['Basenji', 'Basenji'],
      ['Basset Hound', 'Basset Hound'],
      ['Beagle', 'Beagle'],
      ['Bearded Collie', 'Bearded Collie'],
      ['Beauceron', 'Beauceron'],
      ['Bedlington Terrier', 'Bedlington Terrier'],
      ['Belgian Malinois', 'Belgian Malinois'],
      ['Belgian Sheepdog', 'Belgian Sheepdog'],
      ['Belgian Tervuren', 'Belgian Tervuren'],
      ['Bernese Mountain Dog', 'Bernese Mountain Dog'],
      ['Bichon Frise', 'Bichon Frise'],
      ['Black and Tan Coonhound', 'Black and Tan Coonhound'],
      ['Black Russian Terrier', 'Black Russian Terrier'],
      ['Bloodhound', 'Bloodhound'],
      ['Blue Heeler', 'Blue Heeler'],
      ['Bluetick Coonhound', 'Bluetick Coonhound'],
      ['Bolognese', 'Bolognese'],
      ['Border Collie', 'Border Collie'],
      ['Border Terrier', 'Border Terrier'],
      ['Borzoi', 'Borzoi'],
      ['Boston Terrier', 'Boston Terrier'],
      ['Bouvier des Flandres', 'Bouvier des Flandres'],
      ['Boxer', 'Boxer'],
      ['Boykin Spaniel', 'Boykin Spaniel'],
      ['Bracco Italiano', 'Bracco Italiano'],
      ['Briard', 'Briard'],
      ['Brittany', 'Brittany'],
      ['Brussels Griffon', 'Brussels Griffon'],
      ['Bull Terrier', 'Bull Terrier'],
      ['Bulldog', 'Bulldog'],
      ['Bullmastiff', 'Bullmastiff'],
      ['Cairn Terrier', 'Cairn Terrier'],
      ['Canaan Dog', 'Canaan Dog'],
      ['Cane Corso', 'Cane Corso'],
      ['Cardigan Welsh Corgi', 'Cardigan Welsh Corgi'],
      ['Catahoula Leopard Dog', 'Catahoula Leopard Dog'],
      ['Cavalier King Charles Spaniel', 'Cavalier King Charles Spaniel'],
      ['Cesky Terrier', 'Cesky Terrier'],
      ['Chesapeake Bay Retriever', 'Chesapeake Bay Retriever'],
      ['Chihuahua', 'Chihuahua'],
      ['Chinese Crested Dog', 'Chinese Crested Dog'],
      ['Chinese Shar-Pei', 'Chinese Shar-Pei'],
      ['Chow Chow', 'Chow Chow'],
      ['Clumber Spaniel', 'Clumber Spaniel'],
      ['Cockapoo', 'Cockapoo'],
      ['Cocker Spaniel', 'Cocker Spaniel'],
      ['Collie', 'Collie'],
      ['Corgi', 'Corgi'],
      ['Coton de Tulear', 'Coton de Tulear'],
      ['Curly-Coated Retriever', 'Curly-Coated Retriever'],
      ['Dachshund-Miniature', 'Dachshund-Miniature'],
      ['Dachshund-Standard', 'Dachshund-Standard'],
      ['Dalmatian', 'Dalmatian'],
      ['Dandie Dinmont Terrier', 'Dandie Dinmont Terrier'],
      ['Doberman Pinscher', 'Doberman Pinscher'],
      ['Dogue de Bordeaux', 'Dogue de Bordeaux'],
      ['English Cocker Spaniel', 'English Cocker Spaniel'],
      ['English Foxhound', 'English Foxhound'],
      ['English Setter', 'English Setter'],
      ['English Springer Spaniel', 'English Springer Spaniel'],
      ['English Toy Spaniel', 'English Toy Spaniel'],
      ['Field Spaniel', 'Field Spaniel'],
      ['Finnish Lapphund', 'Finnish Lapphund'],
      ['Finnish Spitz', 'Finnish Spitz'],
      ['Flat-Coated Retriever', 'Flat-Coated Retriever'],
      ['French Bulldog', 'French Bulldog'],
      ['German Pinscher', 'German Pinscher'],
      ['German Shepherd Dog', 'German Shepherd Dog'],
      ['German Shorthaired Pointer', 'German Shorthaired Pointer'],
      ['German Wirehaired Pointer', 'German Wirehaired Pointer'],
      ['Giant Schnauzer', 'Giant Schnauzer'],
      ['Glen of Imaal Terrier', 'Glen of Imaal Terrier'],
      ['Goldador', 'Goldador'],
      ['Golden Retriever', 'Golden Retriever'],
      ['Gordon Setter', 'Gordon Setter'],
      ['Great Dane', 'Great Dane'],
      ['Great Pyrenees', 'Great Pyrenees'],
      ['Greater Swiss Mountain Dog', 'Greater Swiss Mountain Dog'],
      ['Greyhound', 'Greyhound'],
      ['Harrier', 'Harrier'],
      ['Havanese', 'Havanese'],
      ['Ibizan Hound', 'Ibizan Hound'],
      ['Icelandic Sheepdog', 'Icelandic Sheepdog'],
      ['Irish Red and White Setter', 'Irish Red and White Setter'],
      ['Irish Setter', 'Irish Setter'],
      ['Irish Terrier', 'Irish Terrier'],
      ['Irish Water Spaniel', 'Irish Water Spaniel'],
      ['Irish Wolfhound', 'Irish Wolfhound'],
      ['Italian Greyhound', 'Italian Greyhound'],
      ['Jack Russell Terrier', 'Jack Russell Terrier'],
      ['Japanese Chin', 'Japanese Chin'],
      ['Keeshond', 'Keeshond'],
      ['Kerry Blue Terrier', 'Kerry Blue Terrier'],
      ['Komondor', 'Komondor'],
      ['Kooikerhondje', 'Kooikerhondje'],
      ['Korean Jindo Dog', 'Korean Jindo Dog'],
      ['Kuvasz', 'Kuvasz'],
      ['Labrador Retriever', 'Labrador Retriever'],
      ['Lakeland Terrier', 'Lakeland Terrier'],
      ['Lancashire Heeler', 'Lancashire Heeler'],
      ['Leonberger', 'Leonberger'],
      ['Lhasa Apso', 'Lhasa Apso'],
      ['Lowchen', 'Lowchen'],
      ['Maltese', 'Maltese'],
      ['Maltipoo', 'Maltipoo'],
      ['Manchester Terrier-Standard', 'Manchester Terrier-Standard'],
      ['Manchester Terrier-Toy', 'Manchester Terrier-Toy'],
      ['Mastiff', 'Mastiff'],
      ['Miniature Bull Terrier', 'Miniature Bull Terrier'],
      ['Miniature Pinscher', 'Miniature Pinscher'],
      ['Miniature Schnauzer', 'Miniature Schnauzer'],
      ['Mixed Breed', 'Mixed Breed'],
      ['Neapolitan Mastiff', 'Neapolitan Mastiff'],
      ['Newfoundland', 'Newfoundland'],
      ['Norfolk Terrier', 'Norfolk Terrier'],
      ['Norwegian Buhund', 'Norwegian Buhund'],
      ['Norwegian Elkhound', 'Norwegian Elkhound'],
      ['Norwegian Lundehund', 'Norwegian Lundehund'],
      ['Norwich Terrier', 'Norwich Terrier'],
      ['Nova Scotia Duck Tolling Retriever', 'Nova Scotia Duck Tolling Retriever'],
      ['Old English Sheepdog', 'Old English Sheepdog'],
      ['Otterhound', 'Otterhound'],
      ['Papillon', 'Papillon'],
      ['Parson Russell Terrier', 'Parson Russell Terrier'],
      ['Peekapoo', 'Peekapoo'],
      ['Pekingese', 'Pekingese'],
      ['Pembroke Welsh Corgi', 'Pembroke Welsh Corgi'],
      ['Petit Basset Griffon Vendeen', 'Petit Basset Griffon Vendeen'],
      ['Pharaoh Hound', 'Pharaoh Hound'],
      ['Pitbull', 'Pitbull'],
      ['Plott', 'Plott'],
      ['Pocket Beagle', 'Pocket Beagle'],
      ['Pointer', 'Pointer'],
      ['Polish Lowland Sheepdog', 'Polish Lowland Sheepdog'],
      ['Pomeranian', 'Pomeranian'],
      ['Poodle-Miniature', 'Poodle-Miniature'],
      ['Poodle-Standard', 'Poodle-Standard'],
      ['Poodle-Toy', 'Poodle-Toy'],
      ['Portuguese Water Dog', 'Portuguese Water Dog'],
      ['Pug', 'Pug'],
      ['Puli', 'Puli'],
      ['Pyrenean Shepherd', 'Pyrenean Shepherd'],
      ['Rat Terrier', 'Rat Terrier'],
      ['Redbone Coonhound', 'Redbone Coonhound'],
      ['Rhodesian Ridgeback', 'Rhodesian Ridgeback'],
      ['Rottweiler', 'Rottweiler'],
      ['Saint Bernard', 'Saint Bernard'],
      ['Saluki', 'Saluki'],
      ['Gazelle Hound', 'Gazelle Hound'],
      ['Samoyed', 'Samoyed'],
      ['Schipperke', 'Schipperke'],
      ['Schnoodle', 'Schnoodle'],
      ['Scottish Deerhound', 'Scottish Deerhound'],
      ['Scottish Terrier', 'Scottish Terrier'],
      ['Sealyham Terrier', 'Sealyham Terrier'],
      ['Shetland Sheepdog', 'Shetland Sheepdog'],
      ['Shiba Inu', 'Shiba Inu'],
      ['Shih Tzu', 'Shih Tzu'],
      ['Siberian Husky', 'Siberian Husky'],
      ['Silky Terrier', 'Silky Terrier'],
      ['Skye Terrier', 'Skye Terrier'],
      ['Sloughi', 'Sloughi'],
      ['Small Munsterlander Pointer', 'Small Munsterlander Pointer'],
      ['Smooth Fox Terrier', 'Smooth Fox Terrier'],
      ['Soft Coated Wheaten Terrier', 'Soft Coated Wheaten Terrier'],
      ['Spinone Italiano', 'Spinone Italiano'],
      ['Stabyhoun', 'Stabyhoun'],
      ['Staffordshire Bull Terrier', 'Staffordshire Bull Terrier'],
      ['Standard Schnauzer', 'Standard Schnauzer'],
      ['Sussex Spaniel', 'Sussex Spaniel'],
      ['Swedish Vallhund', 'Swedish Vallhund'],
      ['Tibetan Mastiff', 'Tibetan Mastiff'],
      ['Tibetan Spaniel', 'Tibetan Spaniel'],
      ['Tibetan Terrier', 'Tibetan Terrier'],
      ['Toy Fox Terrier', 'Toy Fox Terrier'],
      ['Treeing Tennessee Brindle', 'Treeing Tennessee Brindle'],
      ['Treeing Walker Coonhound', 'Treeing Walker Coonhound'],
      ['Vizsla', 'Vizsla'],
      ['Weimaraner', 'Weimaraner'],
      ['Welsh Springer Spaniel', 'Welsh Springer Spaniel'],
      ['Welsh Terrier', 'Welsh Terrier'],
      ['West Highland White Terrier', 'West Highland White Terrier'],
      ['Whippet', 'Whippet'],
      ['Wire Fox Terrier', 'Wire Fox Terrier'],
      ['Wirehaired Pointing Griffon', 'Wirehaired Pointing Griffon'],
      ['Xoloitzcuintli', 'Xoloitzcuintli'],
      ['Yorkipoo', 'Yorkipoo'],
      ['Yorkshire Terrier', 'Yorkshire Terrier']
    ]
  end
end
